version: '3'
services:
    mongodb:
        image: mongo:bionic
        container_name: mongo
        restart: always
        volumes:
            - .mongodb/data:/data/db
        ports:
            - "27017:27017"
        command: --storageEngine wiredTiger
